[package]
name = "chain-connector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chain-data = { workspace = true }
chain-types = { workspace = true }
ethabi = { workspace = true }
jsonrpsee = { workspace = true, features = ["macros", "server", "client"] }
eyre = { workspace = true }
fluence-libp2p = { workspace = true }
serde_json = { workspace = true }
clarity = "1.3.0"
hex = { workspace = true }
server-config = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
mockito = { workspace = true }
