[package]
name = "nox-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dev-dependencies]
uuid-utils = { workspace = true }
test-utils = { workspace = true }
service-modules = { workspace = true }
nox = { workspace = true }
particle-modules = { workspace = true }
particle-execution = { workspace = true }
particle-args = { workspace = true }
created-swarm = { workspace = true }
connected-client = { workspace = true }
test-constants = { workspace = true }
toy-vms = { workspace = true }
now-millis = { workspace = true }
local-vm = { workspace = true }
control-macro = { workspace = true }
json-utils = { workspace = true }
system-services = { workspace = true }
subnet-resolver = { workspace = true }
fs-utils = { workspace = true }

log-utils = { workspace = true }
fluence-spell-dtos = { workspace = true }
fluence-app-service = { workspace = true }
particle-protocol = { workspace = true }
particle-builtins = { workspace = true }
connection-pool = { workspace = true }
aquamarine = { workspace = true }
sorcerer = { workspace = true }
fluence-keypair = { workspace = true }
key-manager = { workspace = true }
fluence-libp2p = { workspace = true }
humantime-serde = "1.1.1"

spell-event-bus = { workspace = true }
parking_lot = { workspace = true }
maplit = { workspace = true }
serde_json = { workspace = true }
fstrings = { workspace = true }
serde = { workspace = true }
multihash = { workspace = true }
blake3 = "1.5.0"
rand = "0.8.5"
bs58 = { workspace = true }
eyre = { workspace = true }
libp2p = { workspace = true }
libp2p-kad = { workspace = true }
itertools = "0.11.0"
futures = { workspace = true }
base64 = { workspace = true }

tokio = { workspace = true }
log = { workspace = true }
tracing = { workspace = true }
mockito = "1.2.0"
